version: '3.8'
services:
  db:
    image: postgres:13
    container_name: kinokuniya_db
    environment:
      - POSTGRES_USER=kinokuniya_user
      - POSTGRES_PASSWORD=kinokuniya_password
      - POSTGRES_DB=kinokuniya_db
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
    volumes:
      - kinokuniya_data:/var/lib/postgresql/data
    networks:
      - kinokuniya_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: kinokuniya_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - kinokuniya_network

networks:
  kinokuniya_network:
    driver: bridge

volumes:
  kinokuniya_data:
    driver: local
