services:
  - type: web
    name: kinokuniya-flask-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: POSTGRES_USER
        fromDatabase:
          name: kinokuniya-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: kinokuniya-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: kinokuniya-db
          property: database
      - key: POSTGRES_HOST
        fromDatabase:
          name: kinokuniya-db
          property: host
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000

  - type: postgresql
    name: kinokuniya-db
    plan: free